name: scanner
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
env:
  IMAGE: "nginx:perl"
  REGISTRY: "Docker Hub"
  BUILD_JOB_NAME: "Github-Action-Sample"
  BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/
  BUILD_NUMBER: ${{ github.run_id }}
  AQUA_EMAIL: ${{ secrets.AQUA_EMAIL }}
  AQUA_PASS: ${{ secrets.AQUA_PASS }}
  AQUA_SERVER: ${{ secrets.AQUA_SERVER }}
jobs:
  scanner:
    name: scanning-image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Aqua Credentials
        run: |
          wget --user "$AQUA_EMAIL" --password "$AQUA_PASS" https://download.aquasec.com/scanner/2022.4/scannercli
      - name: Aqua Scanner
        run: |
          chmod +x scannercli
          ./scannercli scan -U "$AQUA_EMAIL" -P "$AQUA_PASS" -H "$AQUA_SERVER" "$IMAGE" --registry "$REGISTRY"
